export default function Page() {
  return (
    <main className="min-h-screen grid place-items-center p-8">
      <div className="max-w-xl text-center space-y-4">
        <h1 className="text-3xl font-semibold">Replication Ready</h1>
        <p className="text-white/70">Pages will be generated by the replicator under this app directory.</p>
      </div>
    </main>
  );
}


